### ISSUE TITLE
about depth/distance estimation formula

### ISSUE THREAD

**Issue by ynma-hanvo** [shun74/Fisheye-Depth-Estimation#1]
thanks for sharing your work, it is great.

I have question about the formula in depthestimation.py  line 62 to 64,  can you discrible about it. 
and how to generate points from it.

**Comment by shun74** [comment]
@ynma-hanvo 

Thank you for your question about my Python implementation.

> I have question about the formula in depthestimation.py line 62 to 64, can you discrible about it.
and how to generate points from it.

To be clear, the Python code was intentionally created for prototyping purposes and remains incomplete. For a correct understanding, please refer to the C++ implementation in `src/utils/undistort_utils.cpp` and `src/engines/pcd_generator.cpp`.
