### ISSUE TITLE
There is a “Segmentation fault (core dumped)“ issue

### ISSUE THREAD

**Issue by snailsssss** [shun74/Fisheye-Depth-Estimation#2]
Fisheye-Depth-Estimation-main$ sh scripts/calib.sh
Segmentation fault (core dumped)
![Uploading Screenshot from 2024-01-15 13-08-22.png…]()

**Comment by snailsssss** [comment]
![Screenshot from 2024-01-15 13-08-22](https://github.com/shun74/Fisheye-Depth-Estimation/assets/104705319/675be054-8167-4eac-833d-3c3584e510dc)

**Comment by shun74** [comment]
@snailsssss 
Could you describe your situation with details?
* Your environment. OS, OpenCV version and so on .
* What did you try. (Ex. Cloned repo than just execute.)
* Other things to add if you have. 

Anyway, thank you for your interest to my project.
