### ISSUE TITLE
Why fov=2.5 in calibration.conf?

### ISSUE THREAD

**Issue by jorgejgnz** [shun74/Fisheye-Depth-Estimation#3]
I'm trying to calibrate a different fisheye stereo camera but the `fov` parameter does not seems to correspond the specification of the camera. In your example, as the camera is fisheye is expected to have 160-180º of FOV but its 2.5 in `calibration.conf`.

If I use a value of 2.5 with my images, the resulting reconstructed images are too deformed:
![2-5](https://github.com/user-attachments/assets/c81690d3-f2c6-4dcf-b35a-01c1e20d2e36)
(It works fine with your images)

If I use a value of 160 or 180, the reconstructed images seems right but very pixelated in the center:
![160](https://github.com/user-attachments/assets/5fccc015-bea3-4ad5-a0a0-cb22e993cccd)

If I user a value of 5-30, the reconstructed images seem right but the images are not symmetric.
![30](https://github.com/user-attachments/assets/70fc4c27-c458-4158-90f5-6706ee0ed15c)

What does this parameter means?
How can I find the optimum value for my camera?

Thank you

**Comment by shun74** [comment]
Thank you for trying my project.

In my experience, the optimal value for this "fov" parameter equals the tangent of half the angle.
Therefore, you can find the correct value by calculating `tan(rad/2)`, where rad represents your camera's horizontal angle.

Please try this calculation and let me know the result.

**Comment by jorgejgnz** [comment]
Thank you! I'm now having better results as you can see in the following images.
However, I'm not having perfectly symmetrical images as then one I can obtain with your samples.
I've performed calibration for different values of horizontal FOV (I don't know real horizontal FOV of my camera)

`FOV = 160º --> tan(rad/2) = 5.67128181962`
![160-as-rad](https://github.com/user-attachments/assets/1bb2c78f-66d6-4733-817e-af2254ce48f3)

`FOV = 170º --> tan(rad/2) = 11.4300523028`
![170-as-rad](https://github.com/user-attachments/assets/209a5695-d8e6-44e8-ac85-540d1a59a818)

`FOV = 180º --> tan(rad/2) = Infinite`
`FOV = 179º --> tan(rad/2) = 114.588650129`
![179-as-rad](https://github.com/user-attachments/assets/864b3d9b-2d9b-4444-b317-7e203b20ba22)

`Expected result (FOV ~136.4)`
![demo](https://github.com/user-attachments/assets/efe788d7-ca6d-4897-9978-32baf3c7a842)

- Shouldn't real FOV value be obtained as a result of camera calibration, from the intrinsic matrix?
- In my images, the yellow line is not in the center, is this indicating some error?

**Comment by shun74** [comment]
> However, I'm not having perfectly symmetrical images as then one I can obtain with your samples.

Actually, it's not a calibration result image always should be symmetric. We sometime get asymmetric result, but it's also correct.
It depends on your camera intrinsic parameter. For example, if `cx` parameter is not close to center, it causes asymmetric distortion.
In many cases, it's good for you to check a normal undistorted result once(not an equirectangle one but rectified one).

> Shouldn't real FOV value be obtained as a result of camera calibration, from the intrinsic matrix?

I checked offical document here. It's called as `fov_scale`.
https://docs.opencv.org/3.4/db/d58/group__calib3d__fisheye.html#gac1af58774006689056b0f2ef1db55ecc
It seems like this parameter can multiply `fx` and `fy` estimated by the calibration process. I'm sure that it directly affects to undistorted result image, but I still can't figure out the way to get appropriate value for this parameter.
At least we have to set this parameter to some value that can avoid image truncation.

> In my images, the yellow line is not in the center, is this indicating some error?

As you can see from my implementation, this yellow line is just hard coded.
https://github.com/shun74/Fisheye-Depth-Estimation/blob/2a2aa1281911164b6555dcab8126e6dedc809169/app/calibration.cpp#L67
If you want to check the epipolar line of images, please adjust this code for fitting your image size.

**Comment by jorgejgnz** [comment]
Thank you for the answer!

I recently discovered my camera has actually 200º of FOV so in my case `tan(rad/2) = tan((200*pi/180)/2) = -5.67128181`. However, if I use this value I still get invalid images after calibration:

![-5](https://github.com/user-attachments/assets/1f2e029c-ab65-42ce-9111-46273db209cf)

- Does this method fail for FOVs >180? Am I doing something wrong?
- If it's not possible with this method, how can I calibrate and undistort images with FOV >180?

Thank you!

**Comment by shun74** [comment]
Thank you for sharing your  cam's details.

For cameras having above 180° of FOV, OpenCV supports the omnidierctional camera model.
Unfortunately, I haven't studied about that model, so I can't really help.
In my codes, I tried to deal with the omnidierctional model. But it's left incomplete and doesn't work correctly.

I recommend you to check the official documentation here.
https://docs.opencv.org/4.x/dd/d12/tutorial_omnidir_calib_main.html
